# Generated by Django 2.0.5 on 2020-01-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(through='game.PlayerGameInfo', to='game.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='attempt_qty',
            field=models.IntegerField(default=0, verbose_name='Кол-во попыток'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='number_hidden',
            field=models.IntegerField(default=None, verbose_name='Загаданное число'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='number_try',
            field=models.IntegerField(default=0, verbose_name='Введённое число'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
