# Generated by Django 2.0.5 on 2020-01-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
